# This file has been generated by node2nix 1.1.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "passive-voice-0.0.1" = {
      name = "passive-voice";
      packageName = "passive-voice";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/passive-voice/-/passive-voice-0.0.1.tgz";
        sha1 = "6a9e1fbc1ca74b57ac35f0fcf8abb450bfca2ac8";
      };
    };
    "weasel-words-0.1.1" = {
      name = "weasel-words";
      packageName = "weasel-words";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/weasel-words/-/weasel-words-0.1.1.tgz";
        sha1 = "7137946585c73fe44882013853bd000c5d687a4e";
      };
    };
    "adverb-where-0.0.9" = {
      name = "adverb-where";
      packageName = "adverb-where";
      version = "0.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/adverb-where/-/adverb-where-0.0.9.tgz";
        sha1 = "09c5cddd8d503b9fe5f76e0b8dc5c70a8f193e34";
      };
    };
    "too-wordy-0.1.4" = {
      name = "too-wordy";
      packageName = "too-wordy";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/too-wordy/-/too-wordy-0.1.4.tgz";
        sha1 = "8e7b20a7b7a4d8fc3759f4e00c4929993d1b12f0";
      };
    };
    "no-cliches-0.1.0" = {
      name = "no-cliches";
      packageName = "no-cliches";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/no-cliches/-/no-cliches-0.1.0.tgz";
        sha1 = "f4eb81a551fecde813f8c611e35e64a5118dc38c";
      };
    };
  };
in
{
  write-good = nodeEnv.buildNodePackage {
    name = "write-good";
    packageName = "write-good";
    version = "0.10.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/write-good/-/write-good-0.10.2.tgz";
      sha1 = "9347173f2cbcf46e5600d321c78d4e5c4ebb5933";
    };
    dependencies = [
      sources."passive-voice-0.0.1"
      sources."weasel-words-0.1.1"
      sources."adverb-where-0.0.9"
      sources."too-wordy-0.1.4"
      sources."no-cliches-0.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Naive linter for English prose";
      homepage = "https://github.com/btford/write-good#readme";
      license = "MIT";
    };
    production = true;
  };
}